# Generated by Django 3.1.7 on 2021-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_predictions_true_predict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='true_predict',
            field=models.IntegerField(blank=True, null=True, verbose_name='Was_prediction_true'),
        ),
    ]
